#pragma once

#ifndef __ENUM_H__
#define __ENUM_H__

namespace BULLET
{
	//안쓰는거 하나씩 나중에 정리할게요
	enum DIR { LEFT, RIGHT, UP, DOWN, BASIC, RECT, MINTORNADO, TORNADO, BIGTORNADO, BARRIER, MONSTER_BASICRD, MONSTER_BASICLD, MONSTER_BASICLU, MONSTER_BASICRU, ANGLE, END };
}

namespace OBJID
{
	enum ID { PLAYER, MONSTER, MONSTER_KAMIKAZE, MONSTER_1, BOSS, BULLET, MOUSE, END };
}

#endif // !__ENUM_H__