#pragma once

#ifndef __ENUM_H__
#define __ENUM_H__

namespace BULLET
{
	//안쓰는거 하나씩 나중에 정리할게요
	enum DIR { LEFT, RIGHT, UP, DOWN, BASIC, RECT, MINTORNADO, TORNADO, BIGTORNADO, BARRIER, MONSTER_BASICRD, MONSTER_BASICLD, MONSTER_BASICLU, MONSTER_BASICRU, ANGLE, DIR_END};
	enum SHAPE { CIRCLE, ELLIPSE, SHAPE_END };
}

namespace OBJID
{
	enum ID { PLAYER, MONSTER, MONSTER_KAMIKAZE, MONSTER_1, BOSS, BULLET, PLAYER_BULLET, MOUSE, END };
}
namespace BOSS
{
	enum STATE { P1_IDLE, END};
}

#endif // !__ENUM_H__